"use client";

import Link from "next/link";
import Image from "next/image";
import * as Dialog from "@radix-ui/react-dialog";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { RecipeListResponse } from "@/lib/public-recipes/types";
import styles from "./feature.module.css";

const typeLabel = (type: string) => type === "FINISHED_PRODUCT" ? "Thành phẩm" : "Bán thành phẩm";

export default function CatalogueClient({ result, query }: { result: RecipeListResponse; query: { search: string; type: string; categoryId: string; sort: "newest" | "name" | "cost"; page: number } }) {
  const router = useRouter();
  const [search, setSearch] = useState(query.search);
  const [filterOpen, setFilterOpen] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  const update = (next: Partial<typeof query>) => { const values = { ...query, ...next }; const qs = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => { if (value && value !== "newest" && value !== 1) qs.set(key, String(value)); }); router.push(`/cong-thuc${qs.toString() ? `?${qs}` : ""}`); setFilterOpen(false); };
  useEffect(() => { const handle = (event: KeyboardEvent) => { if (event.key === "/" && document.activeElement !== searchRef.current) { event.preventDefault(); searchRef.current?.focus(); } }; document.addEventListener("keydown", handle); return () => document.removeEventListener("keydown", handle); }, []);
  const clear = () => { setSearch(""); update({ search: "", type: "", categoryId: "", page: 1 }); };
  return <main className={styles.main}><section className={`${styles.hero} ${styles.wrap}`}><div><span className={styles.eyebrow}>Diệp Trà / Công thức chuẩn hóa</span><h1>Để mỗi ly trà bắt đầu từ một nền tảng tốt.</h1><p>Thư viện công thức pha chế dành cho đối tác F&amp;B. Từ nền trà, bán thành phẩm đến ly hoàn thiện, mọi thông tin được trình bày để đội ngũ dễ thử nghiệm và chuyển giao.</p></div><div className={styles.heroNote}><strong>Tra cứu nhanh, pha chế nhất quán.</strong>Chọn một công thức để xem định lượng, quy trình và tài liệu tải về.</div></section>
    <section className={`${styles.toolbar} ${styles.wrap}`}><div className={styles.chips}>{[{ value: "", label: "Tất cả" }, { value: "FINISHED_PRODUCT", label: "Thành phẩm" }, { value: "SEMI_FINISHED", label: "Bán thành phẩm" }].map(type => <button key={type.value || "all"} className={styles.chip} aria-pressed={query.type === type.value} onClick={() => update({ type: type.value, page: 1 })}>{type.label}</button>)}</div><div className={styles.toolbarRight}><form onSubmit={event => { event.preventDefault(); update({ search, page: 1 }); }}><label htmlFor="recipe-search" className="sr-only">Tìm công thức</label><input ref={searchRef} id="recipe-search" className={styles.select} type="search" value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === "Escape") { event.preventDefault(); setSearch(""); update({ search: "", page: 1 }); searchRef.current?.blur(); } }} placeholder="Tìm công thức…" aria-label="Tìm công thức" /></form><button className={`${styles.button} ${styles.mobileFilterButton}`} onClick={() => setFilterOpen(true)}>Bộ lọc</button><span>{result.total} công thức</span><label htmlFor="recipe-sort" className="sr-only">Sắp xếp</label><select id="recipe-sort" className={styles.select} value={query.sort} onChange={event => update({ sort: event.target.value as typeof query.sort, page: 1 })}><option value="newest">Mới nhất</option><option value="name">A–Z</option><option value="cost">Chi phí thấp đến cao</option></select></div></section>
    <section className={`${styles.catalogue} ${styles.wrap}`}><div className={styles.resultsHead}><h2>{query.categoryId ? result.categories.find(category => String(category.id) === query.categoryId)?.name || "Công thức" : "Tất cả công thức"}</h2><span className={styles.resultHint}>{query.search ? `Kết quả cho “${query.search}”` : "Cập nhật theo mùa và nhu cầu quầy"}</span></div>{result.data.length ? <><div className={styles.grid}>{result.data.map(recipe => <article className={styles.card} key={recipe.slug}><Link href={`/cong-thuc/${recipe.slug}`} aria-label={`Xem công thức ${recipe.name}`}><div className={styles.cardImage}>{recipe.thumbnail ? <Image src={recipe.thumbnail} alt={recipe.name} fill sizes="(max-width: 800px) 100vw, 33vw" unoptimized /> : <div className={styles.fallback}>Ảnh công thức đang được cập nhật</div>}</div><div className={styles.kicker}><span className={styles.dot} />{typeLabel(recipe.type)}{recipe.category ? ` · ${recipe.category.name}` : ""}</div><h3>{recipe.name}</h3><p>{recipe.description || "Công thức chuẩn hóa dành cho vận hành quầy pha chế."}</p><div className={styles.mediaMeta} role="list" aria-label={`Media của ${recipe.name}`}><span className={styles.mediaItem} role="listitem">Ảnh {recipe.mediaCounts.images}</span>{recipe.mediaCounts.videos > 0 && <span className={styles.mediaItem} role="listitem">Video {recipe.mediaCounts.videos}</span>}<span className={styles.mediaItem} role="listitem">PDF</span></div></Link></article>)}</div><nav className={styles.pagination} aria-label="Phân trang catalogue">{result.page > 1 && <button className={styles.button} onClick={() => update({ page: result.page - 1 })}>Trang trước</button>}<span>Trang {result.page}</span>{result.page * result.limit < result.total && <button className={styles.button} onClick={() => update({ page: result.page + 1 })}>Trang tiếp theo</button>}</nav></> : <div className={styles.empty}><h3>Chưa có công thức phù hợp</h3><p>Thử xóa từ khóa hoặc chọn lại bộ lọc để xem thêm.</p><button className={styles.button} onClick={clear}>Xóa bộ lọc</button></div>}</section>
    <Dialog.Root open={filterOpen} onOpenChange={setFilterOpen}><Dialog.Portal><Dialog.Overlay className={styles.filterOverlay} /><Dialog.Content className={styles.filterSheet} aria-describedby={undefined}><Dialog.Title id="filter-heading">Bộ lọc catalogue</Dialog.Title><label htmlFor="mobile-category">Nhóm công thức</label><select id="mobile-category" className={styles.select} value={query.categoryId} onChange={event => update({ categoryId: event.target.value, page: 1 })}><option value="">Mọi nhóm</option>{result.categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><div className={styles.actions}><Dialog.Close className={`${styles.button} ${styles.primary}`}>Xem kết quả</Dialog.Close><button className={styles.button} onClick={clear}>Xóa bộ lọc</button></div></Dialog.Content></Dialog.Portal></Dialog.Root></main>;
}
